plugins {
    id("java")
    id 'net.neoforged.moddev' version '1.0.21'
}

neoForge {
//    minecraft = "1.21.1"
    version = "21.1.172"
}

version = "${minecraft_version}-neoforge-${mod_version}"
group = mod_group_id

base {
    archivesName = "${mod_jar_name}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { url = "https://maven.neoforged.net/releases" }
    maven { name = "Progwml6 maven"; url = "https://dvs1.progwml6.com/files/maven/" }
    maven { name = "ModMaven"; url = "https://modmaven.k-4u.nl" }
    maven { url = "https://maven.theillusivec4.top/" }
    maven { name = "CurseMaven"; url = "https://cursemaven.com/" }
}

dependencies {

    compileOnly("org.spongepowered:mixin:0.8.5")
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))

//    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
//    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
//    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}+${minecraft_version}:api"
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}+${minecraft_version}"
    implementation "curse.maven:shoulder-surfing-reloaded-243190:5419215"
}
